name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" >> ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config
          sudo apt install sshpass

      - name: Stop and Remove Previous
        working-directory: ./
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          echo "Running commands on VPS"
          cd ~/sites/me
          pm2 stop me
          cd ~/sites
          rimraf ~/sites/me
          EOF

      - name: Build and Start New
        working-directory: ./
        env:
          NODE_ENV: production
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
          echo "Running commands on VPS"
          cd ~/sites
          git clone git@github.com:hasanirogers/me.git --branch main
          cd ~/sites/me
          cat > .env <<EOL
          NODE_ENV=production
          SENDGRID_API_KEY=$SENDGRID_API_KEY
          EOL
          npm install
          npm run build
          pm2 start "npm run serve" --name "me"
          EOF
